-- SELECT * from employees
-- SELECT * FROM "public"."employees"
-- select count( * ) from departments 
-- SELECT (count( * ) - 1)  as "Number of Raises" FROM salaries WHERE emp_no = 10001
-- SELECT title as "Title" FROM titles where emp_no = 10006
-- select emp_no as "Employee #", birth_date as "Birthday", first_name as "First Name" from employees;
-- SELECT * from employees;
